### PR TITLE
Publish msg: headers passed by structure

### LINKED ISSUE #14: [Bug] Send Msg headers parse function can crash LabVIEW
### Describe the bug

Current version of send function will filter out the header that value containes 0x3B or 0x3D byte in content. This leads to issues when sending integers like timestamp
(in the range of one year, 0x3B or 0x3D will appear more then 1M times).

### Expected Behavior

Any value of headers should be possible to send. To tackle this we should consider to change how headers as send to C share library using Rolf idea:
https://lavag.org/topic/23965-pass-complex-data-structure-to-c-function/#comment-186770

### Steps To Reproduce

_No response_

### Exceptions (if any)

_No response_

### Version

_No response_

### PR DESCRIPTION
**Pull request by kwitekrac**
Message headers in "Publish" operation are send using structure istead of string. 

## Checklist

- [x] I have used a PR title that is descriptive enough for a release note.
- [x] I have tested these changes locally.
- [ ] I have added appropriate tests or updated existing tests.
- [ ] I have tested these changes on a dedicated VM or a customer VM [name of the VM]
- [ ] I have added appropriate documentation or updated existing documentation.

### CODE REVIEW

File: labview/labview_types.h [hunk 1]
```diff
@@ -3,6 +3,26 @@
...
 #define LABVIEW_TYPES_H
 
+/**
+ * Structure that represents LabVIEW Cluster (items: string key, string value, int32 dataType)
+ */
+typedef struct {
+	LStrHandle key;
+	LStrHandle value;
+    int32_t dataType;
+} KeyValuePairRec;
```
Comment (kdevelleZ) [inline labview/labview_types.h:13]: Why suffix Rec?

File: labview/labview_types.h [hunk 2]
```diff
@@ -3,6 +3,26 @@
...
+ * Structure that represents LabVIEW Cluster Array
+*/
+typedef struct {
+	int32_t dimSize;
+	KeyValuePairRec elt[1];
+} KeyValuePairArr;
+/**
+ * Handle to LabVIEW Cluster Array, used to pass it between LabVIEW and C
+*/
+typedef KeyValuePairArr **KeyValuePairArrHdl;
```
Comment (kdevelleZ) [inline labview/labview_types.h:24]: I don't get this typedef

File: labview/labview_types.h (hunk 1 above)
Comment (kwitekrac) [reply labview/labview_types.h:13]: Rec = received

File: labview/labview_types.h (hunk 2 above)
Comment (kwitekrac) [reply labview/labview_types.h:24]: is a handle (pointer to pointer). Handle is send by LabVIEW if we use "adapt to type" for Call library node.

Comment (kwitekrac) [reply labview/labview_types.h:24]: Labview alocates the memory for the structure -> address of the first byte of this structure is a pointer. To make a memory management easy - in case of structure must be realocated (resized etc.) LabVIEW keeps a pointer to a pointer -> handle.

File: labview/labview_rabbitmq.c [hunk 3]
```diff
@@ -218,7 +218,7 @@ int lv_amqp_consume_message(int64_t conn_intptr, int timeout_sec, LStrHandle out
 }
 
 LABVIEW_PUBLIC_FUNCTION
-int lv_amqp_basic_publish(int64_t conn_intptr, uint16_t channel, char *exchange, char *routingKey, uint8_t* msgHeaderBuf, uint64_t msgHeaderBufLen, LStrHandle messageBody, LStrHandle errorDescription)
+int lv_amqp_basic_publish(int64_t conn_intptr, uint16_t channel, char *exchange, char *routingKey, KeyValuePairArrHdl headers,  LStrHandle messageBody, LStrHandle errorDescription)
```
Comment (kdevelleZ) [inline labview/labview_rabbitmq.c:221]: ArrHdl? not very clear suffix

Comment (kwitekrac) [reply labview/labview_rabbitmq.c:221]: Array handle

**Review by kdevelleZ — APPROVED** [review]
